timeout: "1800s"

options:
  machineType: "E2_HIGHCPU_8"
  logging: CLOUD_LOGGING_ONLY

substitutions:
  _SERVICE: "whatsapp"
  _ENV: "staging"
  _REGION: "us-central1"
  _ARTIFACT_REGISTRY: "connectors"
  _TAG: "manual"

steps:
  # ─────────────────────────────────────────────────────────
  # 1) Build image
  # ─────────────────────────────────────────────────────────
  - id: "build-image"
    name: "gcr.io/cloud-builders/docker"
    args:
      - "build"
      - "--no-cache"
      - "-f"
      - "apps/${_SERVICE}/Dockerfile"
      - "-t"
      - "${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_ARTIFACT_REGISTRY}/${_SERVICE}:${_TAG}"
      - "-t"
      - "${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_ARTIFACT_REGISTRY}/${_SERVICE}:latest"
      - "-t"
      - "${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_ARTIFACT_REGISTRY}/${_SERVICE}:${_ENV}"
      - "."
    timeout: "1200s"

  # ─────────────────────────────────────────────────────────
  # 2) Push tags
  # ─────────────────────────────────────────────────────────
  - id: "push-shortsha"
    name: "gcr.io/cloud-builders/docker"
    args:
      - "push"
      - "${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_ARTIFACT_REGISTRY}/${_SERVICE}:${_TAG}"
    waitFor: ["build-image"]

  - id: "push-latest"
    name: "gcr.io/cloud-builders/docker"
    args:
      - "push"
      - "${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_ARTIFACT_REGISTRY}/${_SERVICE}:latest"
    waitFor: ["build-image"]

  - id: "push-env"
    name: "gcr.io/cloud-builders/docker"
    args:
      - "push"
      - "${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_ARTIFACT_REGISTRY}/${_SERVICE}:${_ENV}"
    waitFor: ["build-image"]

  # ─────────────────────────────────────────────────────────
  # 3) Deploy Cloud Run (FAIL-CLOSED)
  # ─────────────────────────────────────────────────────────
  - id: "deploy-cloud-run"
    name: "gcr.io/google.com/cloudsdktool/cloud-sdk:slim"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        set -euo pipefail

        SERVICE_NAME="${_SERVICE}-connector-${_ENV}"
        IMAGE="${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_ARTIFACT_REGISTRY}/${_SERVICE}:${_ENV}"

        SECRETS="WHATSAPP_VERIFY_TOKEN=${_SERVICE}-verify-token-${_ENV}:latest"
        SECRETS="$$SECRETS,WHATSAPP_WEBHOOK_SECRET=${_SERVICE}-webhook-secret-${_ENV}:latest"
        SECRETS="$$SECRETS,REDIS_URL=redis-url-${_ENV}:latest"
        SECRETS="$$SECRETS,WHATSAPP_ACCESS_TOKEN=${_SERVICE}-access-token-${_ENV}:latest"
        SECRETS="$$SECRETS,WHATSAPP_PHONE_NUMBER_ID=${_SERVICE}-phone-number-id-${_ENV}:latest"

        if [ "${_ENV}" = "staging" ]; then
          SECRETS="$$SECRETS,STAGING_OUTBOUND_TOKEN=staging-outbound-token-${_ENV}:latest"
        fi

        gcloud run deploy "$$SERVICE_NAME" \
          --image "$$IMAGE" \
          --region "${_REGION}" \
          --platform managed \
          --allow-unauthenticated \
          --port 8080 \
          --memory 512Mi \
          --cpu 1 \
          --min-instances 0 \
          --max-instances 10 \
          --concurrency 80 \
          --timeout 60s \
          --set-env-vars "NODE_ENV=${_ENV}" \
          --set-secrets "$$SECRETS"

  # ─────────────────────────────────────────────────────────
  # 4) Smoke test: /health
  # ─────────────────────────────────────────────────────────
  - id: "smoke-test-health"
    name: "gcr.io/google.com/cloudsdktool/cloud-sdk:slim"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        set -euo pipefail

        SERVICE_NAME="${_SERVICE}-connector-${_ENV}"
        sleep 10

        SERVICE_URL="$$(gcloud run services describe "$$SERVICE_NAME" --region="${_REGION}" --format='value(status.url)')"
        curl -sf "$$SERVICE_URL/health"
    waitFor: ["deploy-cloud-run"]

  # ─────────────────────────────────────────────────────────
  # 5) Smoke test: /webhook
  # ─────────────────────────────────────────────────────────
  - id: "smoke-test-webhook"
    name: "gcr.io/google.com/cloudsdktool/cloud-sdk:slim"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        set -euo pipefail

        SERVICE_NAME="${_SERVICE}-connector-${_ENV}"
        SERVICE_URL="$$(gcloud run services describe "$$SERVICE_NAME" --region="${_REGION}" --format='value(status.url)')"

        CODE="$$(curl -s -o /dev/null -w '%{http_code}' \
          "$$SERVICE_URL/webhook?hub.mode=subscribe&hub.verify_token=invalid-token&hub.challenge=test")"

        [ "$$CODE" = "200" ] || [ "$$CODE" = "403" ]
    waitFor: ["smoke-test-health"]

images:
  - "${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_ARTIFACT_REGISTRY}/${_SERVICE}:${_TAG}"
  - "${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_ARTIFACT_REGISTRY}/${_SERVICE}:latest"
  - "${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_ARTIFACT_REGISTRY}/${_SERVICE}:${_ENV}"

tags:
  - "connector-${_SERVICE}"
  - "env-${_ENV}"
  - "cloud-run"
